In [29]:
import numpy as np

y_predicted = np.array([0, 1, 0, 1, 0])
y_true= np.array([0.3, 0.5, 0.6, 0.2, 0])

1. Mean Absolute Error (mean of abs difference in predicted and true values)

In [30]:
def mae(y_true,y_predicted):
      total_error=0

      for yt, yp in zip(y_true,y_predicted):
         total_error+=abs(yt-yp)

      print("total error is: ",total_error)
      
      error=total_error/len(y_true)
      return error

mae(y_true,y_predicted)

total error is:  2.2


0.44000000000000006

Using Numpy array functions

In [31]:
np.mean(np.abs(y_true-y_predicted))

0.44000000000000006

Binary Cross Entropy(Log Loss) = -1/n (ylog(yp)+(1-y)log(1-yp)) 

Predicted value cannot be 0 or 1 as log 0 does not exists

In [32]:
np.log([0])

C:\Users\USER\AppData\Local\Temp\ipykernel_2968\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

Replace 0 by 0.0000000000000000001 and 1 by 0.999999999999999999999999

In [33]:
np.log([0.00000000000000000000001])

array([-52.95945714])

In [34]:
epsilon= 1e-15

In [35]:
y_predicted

array([0, 1, 0, 1, 0])

In [36]:
y_predicted_new=[max(i,epsilon) for i in y_predicted]
y_predicted_new

[1e-15, 1, 1e-15, 1, 1e-15]

In [37]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[1e-15, 0.999999999999999, 1e-15, 0.999999999999999, 1e-15]

In [38]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-3.45387764e+01, -9.99200722e-16, -3.45387764e+01, -9.99200722e-16,
       -3.45387764e+01])

In [39]:
np.log(y_predicted)

C:\Users\USER\AppData\Local\Temp\ipykernel_2968\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([-inf,   0., -inf,   0., -inf])

In [41]:
-np.mean(np.sum(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new)))

75.98634754546276